### ISSUE TITLE
Running the "python landmarkPredict.py predictImage  testList.txt" error!

### ISSUE THREAD

**Issue by getengqing** [qiexing/face-landmark-localization#25]
Traceback (most recent call last):
  File "landmarkPredict.py", line 232, in <module>
    func(*sys.argv[2:])
  File "landmarkPredict.py", line 201, in predictImage
    colorface = getRGBTestPart(bbox,M_left,M_right,M_top,M_bottom,colorImage,vgg_height,vgg_width)
  File "landmarkPredict.py", line 78, in getRGBTestPart
    face=img[retiBBox[2]:retiBBox[3],retiBBox[0]:retiBBox[1],:]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by qiexing** [comment]
@getengqing Maybe try to change the last line as img[int(retiBBox[2]):int(retiBBox[3]),int(retiBBox[0]):int(retiBBox[1]),:] ?

**Comment by getengqing** [comment]
thanks! It is ok!
