### ISSUE TITLE
error :RuntimeError: data array has wrong number of channels

### ISSUE THREAD

**Issue by guojingbuaa** [qiexing/face-landmark-localization#26]
Traceback (most recent call last):
  File "landmarkPredict.py", line 252, in <module>
    func(*sys.argv[2:])
  File "landmarkPredict.py", line 231, in predictImage
    vgg_point_net.set_input_arrays(faces.astype(np.float32),data4DL.astype(np.float32))
  File "/home/ggj/lch/caffe/python/caffe/pycaffe.py", line 245, in _Net_set_input_arrays
    return self._set_input_arrays(data, labels)
RuntimeError: data array has wrong number of channels
Segmentation fault (core dumped)

**Comment by chunniunai220ml** [comment]
are you solve the problem???
