### ISSUE TITLE
直接运行.py报了这个错

### ISSUE THREAD

**Issue by yewang0320** [qiexing/face-landmark-localization#28]
Traceback (most recent call last):
  File "landmarkPredict.py", line 239, in <module>
    func(*sys.argv[2:])
  File "landmarkPredict.py", line 218, in predictImage
    vgg_point_net.set_input_arrays(faces.astype(np.float32),data4DL.astype(np.float32))
TypeError: _Net_set_input_arrays() takes exactly 4 arguments (3 given)

**Comment by qiexing** [comment]
@yewang0320 Hi, It's ok on my computer,  do you modify the deploy.prototxt ?

**Comment by yewang0320** [comment]
It's my caffe version, it has a different set_input_arrays function defined in pycaffe.py
